import React from 'react';
import { Finding, Fact } from '@alcatraz/contracts';
import { FileText, AlertTriangle, CheckCircle, Info, Download } from 'lucide-react';

interface ReportData {
  scenario: string;
  facts: Fact[];
  findings: Finding[];
  timestamp: string;
}

function severityColor(s: string): string {
  switch (s) {
    case 'high_risk': return '#dc2626';
    case 'warning': return '#f59e0b';
    case 'review': return '#3b82f6';
    default: return '#6b7280';
  }
}

function generateReportHTML(data: ReportData): string {
  const findingsHTML = data.findings.map(f => {
    const relFacts = data.facts.filter(fact => f.factIds.includes(fact.id));
    return `
      <div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin-bottom:12px;border-left:4px solid ${severityColor(f.severity)}">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px">
          <span style="background:${severityColor(f.severity)}20;color:${severityColor(f.severity)};padding:2px 10px;border-radius:12px;font-size:12px;font-weight:700;text-transform:uppercase">${f.severity.replace('_', ' ')}</span>
          <span style="font-weight:700;text-transform:uppercase;font-size:13px">${f.type.replace('_', ' ')} DETECTED</span>
        </div>
        <p style="color:#111;font-size:14px;margin-bottom:12px">${f.explanation}</p>
        <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;padding:12px">
          <p style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase;margin-bottom:8px">Source Evidence</p>
          ${relFacts.map(fact => `
            <div style="display:flex;justify-content:space-between;align-items:center;font-size:13px;padding:4px 0">
              <span style="color:#374151">${fact.sourceId}</span>
              <code style="background:#fff;border:1px solid #e5e7eb;padding:2px 8px;border-radius:4px">${fact.attribute}: ${fact.value}</code>
            </div>
          `).join('')}
        </div>
      </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Alcatraz AI Analysis Report</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#111;max-width:800px;margin:0 auto;padding:40px 24px}
@media print{body{padding:20px}}</style></head>
<body>
  <div style="text-align:center;margin-bottom:32px;padding-bottom:24px;border-bottom:2px solid #111">
    <h1 style="font-size:28px;font-weight:800;letter-spacing:-0.5px">🛡️ ALCATRAZ AI</h1>
    <p style="font-size:13px;color:#6b7280;text-transform:uppercase;letter-spacing:2px;margin-top:4px">Verification Report</p>
  </div>
  
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px">
    <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:16px">
      <p style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase">Scenario</p>
      <p style="font-size:16px;font-weight:600;margin-top:4px">${data.scenario}</p>
    </div>
    <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:16px">
      <p style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase">Generated</p>
      <p style="font-size:16px;font-weight:600;margin-top:4px">${data.timestamp}</p>
    </div>
    <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:16px">
      <p style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase">Facts Analyzed</p>
      <p style="font-size:16px;font-weight:600;margin-top:4px">${data.facts.length}</p>
    </div>
    <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:16px">
      <p style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase">Findings</p>
      <p style="font-size:16px;font-weight:600;margin-top:4px">${data.findings.length}</p>
    </div>
  </div>

  <h2 style="font-size:18px;font-weight:700;margin-bottom:16px">Findings</h2>
  ${data.findings.length > 0 ? findingsHTML : '<p style="color:#6b7280;text-align:center;padding:32px">No inconsistencies detected.</p>'}
  
  <div style="margin-top:40px;padding-top:24px;border-top:1px solid #e5e7eb;text-align:center">
    <p style="font-size:12px;color:#9ca3af">Generated by Alcatraz AI — "Verify before you act."</p>
    <p style="font-size:11px;color:#9ca3af;margin-top:4px">All processing performed locally on-device. No data was uploaded to external servers.</p>
  </div>
</body></html>`;
}

export function downloadReport(scenario: string, facts: Fact[], findings: Finding[]) {
  const html = generateReportHTML({
    scenario,
    facts,
    findings,
    timestamp: new Date().toLocaleString(),
  });

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `alcatraz-report-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportButton({ scenario, facts, findings }: { scenario: string; facts: Fact[]; findings: Finding[] }) {
  return (
    <button
      onClick={() => downloadReport(scenario, facts, findings)}
      className="flex items-center gap-2 px-4 py-2 bg-gray-900 dark:bg-white dark:text-gray-900 text-white text-sm font-semibold rounded-lg hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors"
    >
      <Download size={16} /> Export Report
    </button>
  );
}
